### ISSUE TITLE
sdFile input should replace C:\FakePath, decode content, and make a file URI

### ISSUE THREAD

**Issue by StartAutomating** [BarRaider/streamdeck-easypi#2]
When using an sdFile, the input text is taken as-is from the file.  Unfortunately, according to the [HTML5 standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) this will always prepend "c:\fakepath\".

This means that every StreamDeck plugin developer using easypi would need to write their own replacement logic.

I suggest that instead of this behavior, the payload and text displays as a file uri.

This should allow various programming languages to work with the file path more effectively.

For instance, in C# or PowerShell, one can simply cast the value to a `[URI]` and get the `.AbsolutePath` property to get the absolute path to the file, regardless of slashing convention or operating system.

**Comment by BarRaider** [comment]
This already resolved inside Stream Deck Tools and is documented. We don't add this logic into EasyPI so that the backend decides what to do.

**Comment by BarRaider** [comment]
https://github.com/BarRaider/streamdeck-tools/wiki/Receiving-a-filename

**Comment by StartAutomating** [comment]
@BarRaider

Thanks for the prompt reply.  Here are a few more things to consider:

1. Bundling the logic into your streamdeck-tools requires one to use both.  While I realize that's your user scenario, it's not everyone's.  This sort of strong coupling makes it more likely that I'd have to create something like easyPI, rather than help you support it.  ( in other word's it's better for the community).  Keeping this logic in easypi prevents you (or others) from having to re-implement it elsewhere.
2. It's a potential security issue in a client browser, not a local app (that can already read your whole filesystem).  In a local app, it's just uglier. `c:\fakepath\` security is really about obscuring device type (again, we're already on the box).
3. There is already a PR for you.  If you will not take the issue, kindly also close the PR.

Thanks!
